import { NextRequest, NextResponse } from "next/server"
import { prisma } from "@/lib/db"

export async function POST(request: NextRequest) {
  try {
    const data = await request.json()

    // Validate required fields
    if (!data.title || !data.overview || !data.year || !data.durationMin || data.rating === undefined || !data.type) {
      return NextResponse.json(
        { message: "Missing required fields" },
        { status: 400 }
      )
    }

    // Create the movie with related data (UUID will be auto-generated by Prisma)
    const movie = await prisma.movie.create({
      data: {
        title: data.title,
        overview: data.overview,
        year: parseInt(data.year),
        durationMin: parseInt(data.durationMin),
        rating: parseFloat(data.rating),
        type: data.type,
        posterUrl: data.posterUrl || null,
        backdropUrl: data.backdropUrl || null,
        genres: {
          create: (data.genreIds || []).map((genreId: string) => ({
            genreId: genreId
          }))
        },
        streamingUrls: {
          create: (data.streamingUrls || []).map((url: any) => ({
            url: url.url,
            quality: url.quality,
            platform: url.platform,
            isActive: url.isActive ?? true
          }))
        }
      },
      include: {
        genres: {
          include: {
            genre: true
          }
        },
        streamingUrls: true
      }
    })

    return NextResponse.json({
      success: true,
      movie,
      message: "Movie created successfully"
    })
  } catch (error) {
    console.error("Error creating movie:", error)

    // Handle specific Prisma errors
    if (error instanceof Error) {
      if (error.message.includes('Foreign key constraint')) {
        return NextResponse.json(
          { message: "Invalid genre ID provided" },
          { status: 400 }
        )
      }
    }

    return NextResponse.json(
      { message: "Internal server error", error: error instanceof Error ? error.message : "Unknown error" },
      { status: 500 }
    )
  }
}

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const topRated = searchParams.get('topRated') === 'true'
    const trending = searchParams.get('trending') === 'true'
    const featured = searchParams.get('featured') === 'true'
    const genreId = searchParams.get('genreId')
    const search = searchParams.get('search')

    // Build where clause based on filters
    const whereClause: any = {}

    // Top rated filter (rating >= 8.0)
    if (topRated) {
      whereClause.rating = {
        gte: 8.0
      }
    }

    // Trending filter (high view count in last 30 days)
    if (trending) {
      whereClause.viewCount = {
        gte: 100 // Movies with at least 100 views are considered trending
      }
    }

    // Featured content filter
    if (featured) {
      whereClause.featuredContent = {
        isNot: null,
        isActive: true
      }
    }

    // Genre filter
    if (genreId) {
      whereClause.genres = {
        some: {
          genreId: genreId
        }
      }
    }

    // Search filter
    if (search) {
      whereClause.OR = [
        {
          title: {
            contains: search,
            mode: 'insensitive'
          }
        },
        {
          overview: {
            contains: search,
            mode: 'insensitive'
          }
        }
      ]
    }

    const movies = await prisma.movie.findMany({
      where: whereClause,
      include: {
        genres: {
          include: {
            genre: true
          }
        },
        credits: {
          include: {
            person: true
          }
        },
        streamingUrls: {
          where: {
            isActive: true
          }
        },
        featuredContent: true,
        heroSection: true
      },
      orderBy: [
        ...(featured ? [{ featuredContent: { sequence: 'asc' as const } }] : []),
        ...(trending ? [{ viewCount: 'desc' as const }] : []),
        ...(topRated ? [{ rating: 'desc' as const }] : []),
        { createdAt: 'desc' as const }
      ]
    })

    const transformedMovies = movies.map(movie => ({
      id: movie.id,
      title: movie.title,
      overview: movie.overview,
      year: movie.year,
      durationMin: movie.durationMin,
      rating: movie.rating,
      type: movie.type,
      posterUrl: movie.posterUrl,
      backdropUrl: movie.backdropUrl,
      viewCount: movie.viewCount,
      genres: movie.genres.map(mg => mg.genre),
      credits: movie.credits,
      streamingUrls: movie.streamingUrls,
      featuredContent: movie.featuredContent,
      heroSection: movie.heroSection
    }))

    return NextResponse.json(transformedMovies)
  } catch (error) {
    console.error("Error fetching movies:", error)
    return NextResponse.json(
      { message: "Internal server error", error: error instanceof Error ? error.message : "Unknown error" },
      { status: 500 }
    )
  }
}